controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - back_left_corner_joint
      - back_right_corner_joint
      - front_left_corner_joint
      - front_right_corner_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

velocity_controller:
  ros__parameters:
    joints:
      - back_left_wheel_joint
      - back_right_wheel_joint
      - front_left_wheel_joint
      - front_right_wheel_joint
      - mid_left_wheel_joint
      - mid_right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100.0
    use_sim_time: true
